export const roulette = [
  {
    value: "3",
    chip: null,
    isActive: false,
    index: 1,
    color: "red",
    isConfirm: false,
    activeChip: null,
    backEndValue: "field_3",
  },
  {
    value: "6",
    chip: null,
    isActive: false,
    index: 1,
    color: "white",
    isConfirm: false,
    activeChip: null,
    backEndValue: "field_6",
  },
  {
    value: "9",
    chip: null,
    isActive: false,
    index: 1,
    color: "red",
    isConfirm: false,
    activeChip: null,
    backEndValue: "field_9",
  },
  {
    value: "12",
    chip: null,
    isActive: false,
    index: 1,
    color: "red",
    isConfirm: false,
    activeChip: null,
    backEndValue: "field_12",
  },
  {
    value: "15",
    chip: null,
    isActive: false,
    index: 1,
    color: "white",
    isConfirm: false,
    activeChip: null,
    backEndValue: "field_15",
  },
  {
    value: "18",
    chip: null,
    isActive: false,
    index: 1,
    color: "red",
    isConfirm: false,
    activeChip: null,
    backEndValue: "field_18",
  },
  {
    value: "2",
    chip: null,
    isActive: false,
    index: 2,
    color: "white",
    isConfirm: false,
    activeChip: null,
    backEndValue: "field_2",
  },
  {
    value: "5",
    chip: null,
    isActive: false,
    index: 2,
    color: "red",
    isConfirm: false,
    activeChip: null,
    backEndValue: "field_5",
  },
  {
    value: "8",
    chip: null,
    isActive: false,
    index: 2,
    color: "white",
    isConfirm: false,
    activeChip: null,
    backEndValue: "field_8",
  },
  {
    value: "11",
    chip: null,
    isActive: false,
    index: 2,
    color: "white",
    isConfirm: false,
    activeChip: null,
    backEndValue: "field_11",
  },
  {
    value: "14",
    chip: null,
    isActive: false,
    index: 2,
    color: "red",
    isConfirm: false,
    activeChip: null,
    backEndValue: "field_14",
  },
  {
    value: "17",
    chip: null,
    isActive: false,
    index: 2,
    color: "white",
    isConfirm: false,
    activeChip: null,
    backEndValue: "field_17",
  },
  {
    value: "1",
    chip: null,
    isActive: false,
    index: 3,
    color: "red",
    isConfirm: false,
    activeChip: null,
    backEndValue: "field_1",
  },
  {
    value: "4",
    chip: null,
    isActive: false,
    index: 3,
    color: "white",
    isConfirm: false,
    activeChip: null,
    backEndValue: "field_4",
  },
  {
    value: "7",
    chip: null,
    isActive: false,
    index: 3,
    color: "red",
    isConfirm: false,
    activeChip: null,
    backEndValue: "field_7",
  },
  {
    value: "10",
    chip: null,
    isActive: false,
    index: 3,
    color: "white",
    isConfirm: false,
    activeChip: null,
    backEndValue: "field_10",
  },
  {
    value: "13",
    chip: null,
    isActive: false,
    index: 3,
    color: "white",
    isConfirm: false,
    activeChip: null,
    backEndValue: "field_13",
  },
  {
    value: "16",
    chip: null,
    isActive: false,
    index: 3,
    color: "red",
    isConfirm: false,
    activeChip: null,
    backEndValue: "field_16",
  },
  {
    value: "1-9",
    chip: null,
    isActive: false,
    index: 4,
    isConfirm: false,
    activeChip: null,
    backEndValue: "low",
  },
  {
    value: "0",
    chip: null,
    isActive: false,
    index: 4,
    className: "bet_two_box1",
    isConfirm: false,
    activeChip: null,
    backEndValue: "field_0",
  },
  {
    value: "10-18",
    chip: null,
    isActive: false,
    index: 4,
    isConfirm: false,
    activeChip: null,
    backEndValue: "high",
  },
  {
    value: "even",
    chip: null,
    isActive: false,
    index: 5,
    isConfirm: false,
    activeChip: null,
    backEndValue: "even",
  },
  {
    value: "red",
    chip: null,
    isActive: false,
    index: 5,
    image: "/img/red_icon.svg",
    isConfirm: false,
    activeChip: null,
    backEndValue: "red",
  },
  {
    value: "black",
    chip: null,
    isActive: false,
    index: 5,
    image: "/img/white_icon.svg",
    isConfirm: false,
    activeChip: null,
    backEndValue: "black",
  },
  {
    value: "odd",
    chip: null,
    isActive: false,
    index: 5,
    isConfirm: false,
    activeChip: null,
    backEndValue: "odd",
  },
];

export const baccarat = [
  {
    value: "11-1",
    chip: null,
    isActive: false,
    index: 1,
    isConfirm: false,
    activeChip: null,
    color: "white",
    name: "闲对 PlayerPair",
    backEndValue: "player_pair",
    appliedChips: 0,
  },
  {
    value: "11-1",
    chip: null,
    isActive: false,
    index: 1,
    isConfirm: false,
    activeChip: null,
    color: "red",
    name: "庄对 BankerPair",
    backEndValue: "banker_pair",
    appliedChips: 0,
  },
  {
    value: "1-1",
    chip: null,
    isActive: false,
    index: 2,
    isConfirm: false,
    activeChip: null,
    name: "闲 Player",
    color: "white",
    backEndValue: "player",
    appliedChips: 0,
  },
  {
    value: "8-1",
    chip: null,
    isActive: false,
    index: 2,
    isConfirm: false,
    activeChip: null,
    name: "和 Tie",
    color: "yellow",
    backEndValue: "tie",
    appliedChips: 0,
  },
  {
    value: "0.95-1",
    chip: null,
    isActive: false,
    index: 2,
    isConfirm: false,
    activeChip: null,
    name: "庄 Banker",
    color: "red",
    backEndValue: "banker",
    appliedChips: 0,
  },
];

export const sicbo = [
  {
    value: "4-10",
    chip: null,
    isActive: false,
    index: 1,
    image: "/img/4-10.svg",
    isConfirm: false,
    activeChip: null,
    backEndValue: "range_small",
  },
  {
    value: "anyTriple",
    chip: null,
    isActive: false,
    index: 1,
    image: "/img/dice/DiceAll.svg",
    isConfirm: false,
    activeChip: null,
    backEndValue: "triple_any",
  },
  {
    value: "11-17",
    chip: null,
    isActive: false,
    index: 1,
    image: "/img/11-17.svg",
    isConfirm: false,
    activeChip: null,
    backEndValue: "range_big",
  },
  {
    value: "triple1",
    chip: null,
    isActive: false,
    index: 2,
    image: "/img/dice/DiceG1.svg",
    isConfirm: false,
    activeChip: null,
    backEndValue: "triple_1",
  },
  {
    value: "triple2",
    chip: null,
    isActive: false,
    index: 2,
    image: "/img/dice/DiceG2.svg",
    isConfirm: false,
    activeChip: null,
    backEndValue: "triple_2",
  },
  {
    value: "triple3",
    chip: null,
    isActive: false,
    index: 2,
    image: "/img/dice/DiceG3.svg",
    isConfirm: false,
    activeChip: null,
    backEndValue: "triple_3",
  },
  {
    value: "triple4",
    chip: null,
    isActive: false,
    index: 2,
    image: "/img/dice/DiceG4.svg",
    isConfirm: false,
    activeChip: null,
    backEndValue: "triple_4",
  },
  {
    value: "triple5",
    chip: null,
    isActive: false,
    index: 2,
    image: "/img/dice/DiceG5.svg",
    isConfirm: false,
    activeChip: null,
    backEndValue: "triple_5",
  },
  {
    value: "triple6",
    chip: null,
    isActive: false,
    index: 2,
    image: "/img/dice/DiceG6.svg",
    isConfirm: false,
    activeChip: null,
    backEndValue: "triple_6",
  },
  {
    value: "5",
    chip: null,
    isActive: false,
    index: 3,
    color: "white",
    isConfirm: false,
    activeChip: null,
    backEndValue: "sum_5",
  },
  {
    value: "7",
    chip: null,
    isActive: false,
    index: 3,
    color: "white",
    isConfirm: false,
    activeChip: null,
    backEndValue: "sum_7",
  },
  {
    value: "9",
    chip: null,
    isActive: false,
    index: 3,
    color: "white",
    isConfirm: false,
    activeChip: null,
    backEndValue: "sum_9",
  },
  {
    value: "11",
    chip: null,
    isActive: false,
    index: 3,
    color: "white",
    isConfirm: false,
    activeChip: null,
    backEndValue: "sum_11",
  },
  {
    value: "13",
    chip: null,
    isActive: false,
    index: 3,
    color: "white",
    isConfirm: false,
    activeChip: null,
    backEndValue: "sum_13",
  },
  {
    value: "15",
    chip: null,
    isActive: false,
    index: 3,
    color: "white",
    isConfirm: false,
    activeChip: null,
    backEndValue: "sum_15",
  },
  {
    value: "17",
    chip: null,
    isActive: false,
    index: 3,
    color: "white",
    isConfirm: false,
    activeChip: null,
    backEndValue: "sum_17",
  },
  {
    value: "4",
    chip: null,
    isActive: false,
    index: 4,
    color: "white",
    isConfirm: false,
    activeChip: null,
    backEndValue: "sum_4",
  },
  {
    value: "6",
    chip: null,
    isActive: false,
    index: 4,
    color: "white",
    isConfirm: false,
    activeChip: null,
    backEndValue: "sum_6",
  },
  {
    value: "8",
    chip: null,
    isActive: false,
    index: 4,
    color: "white",
    isConfirm: false,
    activeChip: null,
    backEndValue: "sum_8",
  },
  {
    value: "10",
    chip: null,
    isActive: false,
    index: 4,
    color: "white",
    isConfirm: false,
    activeChip: null,
    backEndValue: "sum_10",
  },
  {
    value: "12",
    chip: null,
    isActive: false,
    index: 4,
    color: "white",
    isConfirm: false,
    activeChip: null,
    backEndValue: "sum_12",
  },
  {
    value: "14",
    chip: null,
    isActive: false,
    index: 4,
    color: "white",
    isConfirm: false,
    activeChip: null,
    backEndValue: "sum_14",
  },
  {
    value: "16",
    chip: null,
    isActive: false,
    index: 4,
    color: "white",
    isConfirm: false,
    activeChip: null,
    backEndValue: "sum_16",
  },
  {
    value: "singleDice1",
    chip: null,
    isActive: false,
    index: 5,
    image: "/img/dice/Dice1.svg",
    isConfirm: false,
    activeChip: null,
    backEndValue: "single_1",
  },
  {
    value: "singleDice2",
    chip: null,
    isActive: false,
    index: 5,
    image: "/img/dice/Dice2.svg",
    isConfirm: false,
    activeChip: null,
    backEndValue: "single_2",
  },
  {
    value: "singleDice3",
    chip: null,
    isActive: false,
    index: 5,
    image: "/img/dice/Dice3.svg",
    isConfirm: false,
    activeChip: null,
    backEndValue: "single_3",
  },
  {
    value: "singleDice4",
    chip: null,
    isActive: false,
    index: 5,
    image: "/img/dice/Dice4.svg",
    isConfirm: false,
    activeChip: null,
    backEndValue: "single_4",
  },
  {
    value: "singleDice5",
    chip: null,
    isActive: false,
    index: 5,
    image: "/img/dice/Dice5.svg",
    isConfirm: false,
    activeChip: null,
    backEndValue: "single_5",
  },
  {
    value: "singleDice6",
    chip: null,
    isActive: false,
    index: 5,
    image: "/img/dice/Dice6.svg",
    isConfirm: false,
    activeChip: null,
    backEndValue: "single_6",
  },
];

export const diceposition = {
  Dice1_1: {
    transform: "rotate(5deg)",
  },
  Dice1_2: {
    transform: "rotate(65deg)",
  },
  Dice1_3: {
    transform: "rotate(125deg)",
  },
  Dice1_4: {
    transform: "rotate(185deg)",
  },
  Dice1_5: {
    transform: "rotate(245deg)",
  },
  Dice1_6: {
    transform: "rotate(305deg)",
  },
  Dice2_1: {
    transform: "rotate(315deg)",
  },
  Dice2_2: {
    transform: "rotate(15deg)",
  },
  Dice2_3: {
    transform: "rotate(75deg)",
  },
  Dice2_4: {
    transform: "rotate(135deg)",
  },
  Dice2_5: {
    transform: "rotate(195deg)",
  },
  Dice2_6: {
    transform: "rotate(255deg)",
  },
  Dice3_1: {
    transform: "rotate(285deg)",
  },
  Dice3_2: {
    transform: "rotate(345deg)",
  },
  Dice3_3: {
    transform: "rotate(25deg)",
  },
  Dice3_4: {
    transform: "rotate(85deg)",
  },
  Dice3_5: {
    transform: "rotate(165deg)",
  },
  Dice3_6: {
    transform: "rotate(225deg)",
  },
};

export const getDicePosition = (id, value) => {
  return diceposition[`${id}_${value}`];
};
